// This file will be generated by FlutterFire CLI
// Run: flutterfire configure

// Placeholder file - will be replaced when you run flutterfire configure
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you need to run: flutterfire configure',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-pRLcqyxMOq4ezyYJ4MpaES7ICisDWfQ',
    appId: '1:847952495499:web:ef63fe1120e30309a6258e',
    messagingSenderId: '847952495499',
    projectId: 'food-app-fd1ad',
    authDomain: 'food-app-fd1ad.firebaseapp.com',
    storageBucket: 'food-app-fd1ad.firebasestorage.app',
    measurementId: 'G-G79PQ0BS73',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWOutEGIUVXHaLs01sd5iXTb9UbK8d1yw',
    appId: '1:847952495499:ios:7660e96690bc9806a6258e',
    messagingSenderId: '847952495499',
    projectId: 'food-app-fd1ad',
    storageBucket: 'food-app-fd1ad.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAynuHYFaXc-bYyx48oYwVG6B5o3XgwKC8',
    appId: '1:847952495499:android:21826fd598aabeb3a6258e',
    messagingSenderId: '847952495499',
    projectId: 'food-app-fd1ad',
    storageBucket: 'food-app-fd1ad.firebasestorage.app',
  );

}